---
# name: sstedoldi_cv_app
services:
  st_sstedoldi:
    image: sstedoldi_cv:latest
    build:
      context: st_sstedoldi_cv
      dockerfile: Dockerfile
    container_name: st_sstedoldi_cv
    restart: unless-stopped
    env_file:
      - dev.env
    expose:
      - "8501"
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501
    secrets:
      - aws_api_key
      - aws_secret_key
  apache:
    image: httpd:2.4-alpine
    container_name: apache_proxy
    depends_on:
      - st_sstedoldi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/vhost.conf:/usr/local/apache2/conf/vhost.conf:ro
      - ./apache/certs:/usr/local/apache2/conf/certs:ro
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./apache/certs:/etc/letsencrypt
      - ./apache/certbot-logs:/var/log/letsencrypt
    entrypoint: >
      certbot certonly --standalone
        --non-interactive --agree-tos
        --email santtedo@gmail.com
        -d cv.sstedoldi-ml-ai-app.com.ar -d www.sstedoldi-ml-ai-app.com.ar
secrets:
  aws_api_key:
    file: ./secrets/aws_api_key.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
